services:
  llm_dev:
    extends:
      file: docker-compose.cpu.yml
      service: llm_dev
    build:
      args:
        BASE_IMAGE: "pytorch/pytorch:2.7.1-cuda11.8-cudnn9-runtime"
        BACKEND: "cuda"
    environment:
      - BACKEND=cuda
    devices:
      - /dev/kfd
      - /dev/dri
    group_add:
      - video