services:
  llm_dev:
    build:
      context: .
      dockerfile: "Dockerfile"
      args:
        USER_ID: $USER_ID
    environment:
      - HF_HOME=/home/user/.cache/huggingface
      - UV_CACHE_DIR=/home/user/.cache/uv
      - UV_LINK_MODE=symlink
      - BACKEND=cpu
    volumes:
      - ../:/workspace
      - ./:/workspace/.devcontainer:ro
      - ${HF_HOME:-${HOME}/.cache/huggingface}:/home/user/.cache/huggingface
      - ${UV_CACHE_DIR:-${HOME}/.cache/uv}:/home/user/.cache/uv
    security_opt:
      - seccomp:unconfined
    ipc: host
    shm_size: 8g
    network_mode: host
    working_dir: /workspace
    entrypoint: ["/bin/sh"]
    command: ["-c", "while sleep 1000; do :; done"]