services:
  llm_dev:
    extends:
      file: docker-compose.cpu.yml
      service: llm_dev
    build:
      args:
        BACKEND: "cuda"
    environment:
      - BACKEND=cuda
    devices:
      - /dev/kfd
      - /dev/dri
    group_add:
      - video